### ISSUE TITLE
Show classes as FULL automatically 

### ISSUE THREAD

**Issue by denzuko** [Dallas-Makerspace/calendar#16]
- Place on feed as well

**Comment by denzuko** [comment]
Maybe a push notification should go out on three spots left and one spot left then full.

**Comment by clone1018** [comment]
Partial fix in https://github.com/Dallas-Makerspace/calendar/pull/32

**Comment by MikeColeGuru** [comment]
This has been implemented.   The patch that is currently in the system is slowing the site down because it is looking up each class on the event page as two separate SQL queries each to find the open spots.   I have reimplemented this to pull it all when the classes are pulled from the database.

See https://github.com/Dallas-Makerspace/calendar/commit/902c0407f3fc616f6cea2a6f4d5a8389bccf2b26
